"""add_refunded_amount

Revision ID: d7d1ace7023b
Revises: 094c05ba33c3
Create Date: 2026-07-02 16:46:38.662997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7d1ace7023b'
down_revision: Union[str, Sequence[str], None] = '094c05ba33c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_item', sa.Column('refunded_amount', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0.00'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_item', 'refunded_amount')
    # ### end Alembic commands ###
