"""add_idempotency_key_to_order

Revision ID: e192468ef8b1
Revises: cbdb89e66420
Create Date: 2026-06-25 21:30:57.544173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e192468ef8b1'
down_revision: Union[str, Sequence[str], None] = 'cbdb89e66420'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('idempotency_key', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_order_idempotency_key'), 'order', ['idempotency_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_idempotency_key'), table_name='order')
    op.drop_column('order', 'idempotency_key')
    # ### end Alembic commands ###
