"""sync_financial_and_split_models

Revision ID: e95a4a558afb
Revises: a3a8243a4bff
Create Date: 2026-06-29 23:40:52.917011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e95a4a558afb'
down_revision: Union[str, Sequence[str], None] = 'a3a8243a4bff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_order_parent_id'), 'order', ['parent_id'], unique=False)
    op.create_foreign_key(None, 'order', 'order', ['parent_id'], ['id'], ondelete='RESTRICT')
    op.add_column('order_item', sa.Column('prorated_discount', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('order_item', sa.Column('actual_paid_price', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('order_item', sa.Column('refunded_quantity', sa.Integer(), nullable=False))
    op.add_column('order_item', sa.Column('is_fully_refunded', sa.Boolean(), nullable=False))
    op.add_column('product_variant', sa.Column('warehouse_code', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_product_variant_warehouse_code'), 'product_variant', ['warehouse_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_variant_warehouse_code'), table_name='product_variant')
    op.drop_column('product_variant', 'warehouse_code')
    op.drop_column('order_item', 'is_fully_refunded')
    op.drop_column('order_item', 'refunded_quantity')
    op.drop_column('order_item', 'actual_paid_price')
    op.drop_column('order_item', 'prorated_discount')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_index(op.f('ix_order_parent_id'), table_name='order')
    op.drop_column('order', 'parent_id')
    # ### end Alembic commands ###
